import { escape, policyPage } from './layout.mjs';
export const data = { layout: 'base.11ty.js', permalink: '/about/index.html', path: 'about/', title: 'About Trayage & Kyle Reddoch', seoTitle: 'About Trayage & Kyle Reddoch — Trayage for Mac', description: 'Meet Kyle Reddoch, the independent developer behind Trayage and its Blog. Learn how Trayage guides are written, checked, and kept useful.', tags: ['sitePages'], order: 12 };
export default function ({ site, base }) {
  return policyPage({ site, base, informational: true, path: 'about/', title: 'A person behind the app.', intro: 'Trayage is made and published by Kyle Reddoch under the RelayByte brand.', sections: [
    { id: 'kyle-reddoch', title: 'Meet Kyle Reddoch', content: `<p>${escape(site.publisher)} is the independent developer behind Trayage, a Mac app for reviewing Downloads and moving selected files to Trash after confirmation. RelayByte is the brand used for Kyle’s apps.</p><p>Read the <a href="${base}blog/">Trayage Blog</a> for Mac guides and product news, or visit <a href="${escape(site.publisherURL)}">RelayByte</a> to learn more about the brand.</p>` },
    { id: 'editorial', title: 'Useful answers, clear limits', content: `<p>Our guides explain the steps you can take in Finder and where Trayage can help. They distinguish review suggestions from verified facts: matching filenames and file sizes do not prove identical contents, and an older file may still be important.</p><p>Guides link to primary sources such as Apple’s documentation where relevant. Product news refers to released features, with planned work kept on the <a href="${base}roadmap/">roadmap</a>. Screenshots use sample files and identify preview editions when shown.</p><p>AI tools assist with writing and website development. Kyle reviews articles before publication. Each post identifies its author and publication date; substantive revisions receive an updated date.</p>` },
    { id: 'corrections', title: 'Questions and corrections', content: `<p>If a guide needs a correction, include its URL and the step or statement you are asking about. Contact <a href="mailto:${escape(site.email)}">${escape(site.email)}</a>. For app, purchase, and license questions, start with <a href="${base}support/">Support</a>.</p>` }
  ] });
}
