import { escape, icon, arrow } from './layout.mjs';
import { channelIsLive, hasDownload } from './_lib/releases.js';

export const data = {layout:'base.11ty.js', permalink:'/download/index.html', path:'download/', title:'Get Trayage', description:'Download and purchase options for Trayage on Mac. Check the status of the direct and Mac App Store editions.', tags:['sitePages'], order:6};

export default function ({base, site, releases}) {
  const direct = channelIsLive(releases,'direct');
  const apple = channelIsLive(releases,'appStore');
  const directFirst = direct && !apple;
  const introduction = direct && apple
    ? 'Choose how you’d like to get Trayage. Each edition has its own download, purchase, and update path.'
    : direct ? `Download Trayage directly and start your ${site.pricing.trialDays}-day trial. The Mac App Store edition is still in preparation.`
    : apple ? 'Get Trayage through the Mac App Store. The direct edition is still in preparation.'
    : 'Trayage is preparing for release. This is where you’ll find the direct download and Mac App Store edition as each becomes available.';
  const appleCard = `<section class="download-option" id="mac-app-store" aria-labelledby="apple-download-title"><span class="download-channel">${directFirst?'02':'01'} / Through Apple</span><h2 id="apple-download-title">Mac App Store</h2><p class="release-status">${apple?`Available · Version ${escape(releases.appStore.version)}`:'In preparation'}</p><p>${apple?'Free download with in-app purchases.':'Planned as a free download with in-app purchases.'} File review is free; cleanup is available through an optional trial or a one-time unlock.</p><ul><li>Optional ${site.pricing.trialDays}-day cleanup trial through Apple, subject to eligibility; no automatic charge</li><li>Separate US$${site.pricing.oneTimeUSD} one-time in-app unlock; the store shows your local price</li><li>Updates delivered through the App Store</li></ul>${apple?`<a class="${releases.appStore.badgePath?'app-store-badge':'button full'}" href="${escape(releases.appStore.url)}" aria-label="View Trayage on the Mac App Store">${releases.appStore.badgePath?`<img src="${base}${escape(releases.appStore.badgePath)}" alt="Download on the Mac App Store" height="52">`:`View on the Mac App Store ${arrow}`}</a>`:'<p class="channel-unavailable">The App Store link will appear when the listing is live.</p>'}</section>`;
  const directCard = `<section class="download-option" id="direct" aria-labelledby="direct-download-title"><span class="download-channel">${directFirst?'01':'02'} / Direct from RelayByte</span><h2 id="direct-download-title">Download for Mac</h2><p class="release-status">${direct?`Available · Version ${escape(releases.direct.version)}`:'In preparation'}</p><p>${site.checkoutEnabled ? `Install Trayage directly, start your ${site.pricing.trialDays}-day in-app trial, and purchase a license when you’re ready.` : `Start your ${site.pricing.trialDays}-day in-app trial or activate an existing license. New license purchases are still being finalized.`}</p><ul><li>US$${site.pricing.oneTimeUSD} once; no automatic charge after the trial</li><li>Up to ${site.pricing.directDeviceLimit} active Macs per direct license</li><li>A direct license is activated in the direct edition</li></ul>${direct?`<a class="button full" href="${escape(releases.direct.url)}">Download Trayage ${icon('mac')}</a><p class="download-file-details">${escape(releases.direct.format)} · ${escape(releases.direct.size)} · ${escape(releases.direct.architectures)}</p><details class="download-integrity"><summary>Verify your download</summary><p>SHA-256 checksum</p><code>${escape(releases.direct.sha256)}</code><p>${releases.direct.sizeBytes.toLocaleString('en-US')} bytes</p></details>${site.checkoutEnabled?`<a class="text-link" href="${escape(site.links.oneTime)}">Buy a direct license ${arrow}</a>`:'<p class="plan-fine-print">New license purchases are still being finalized. The download, trial, and existing-license activation are available.</p>'}`:'<p class="channel-unavailable">The signed, notarized download will appear after release checks.</p>'}</section>`;
  return `<div class="wrap document-header"><a class="eyebrow back-link" href="${base}">← Back to Trayage</a><p class="eyebrow page-kicker">Made for your Mac</p><h1>${hasDownload(releases)?'A clearer Downloads<br>folder starts here.':'A little more time<br>in the tray.'}</h1><p class="lede">${introduction}</p><p class="document-meta">macOS ${escape(releases.minimumMacOS)} and later</p></div>
  <div class="wrap download-options">${directFirst?directCard+appleCard:appleCard+directCard}</div>
  <section class="wrap download-help"><h2>The same considered approach.</h2><p>Both editions review files locally and ask before moving selected files to Trash. Your purchase is managed through the channel you choose. A direct license key does not unlock an App Store purchase, and an Apple purchase does not issue a direct license key.</p><p>Version ${site.pricing.majorVersion}.x updates are included. Future major upgrades are optional, with discounted pricing planned for existing owners. See the <a href="${base}terms/">purchase terms</a> for details.</p><div class="download-help-links"><a class="text-link" href="${base}roadmap/">Follow the roadmap ${arrow}</a><a class="text-link" href="${base}changelog/">What’s new ${arrow}</a><a class="text-link" href="${base}support/">Get help ${arrow}</a></div></section>`;
}
