import { hasDownload, channelIsLive } from './_lib/releases.js';
import { icon, arrow, escape } from './layout.mjs';

export function home(base, site, releases) {
  const direct = channelIsLive(releases, 'direct');
  const apple = channelIsLive(releases, 'appStore');
  const availability = direct && apple
    ? 'Choose the direct download or Mac App Store edition on our download page. Each edition has its own purchase and update path.'
    : direct ? 'Download Trayage directly for your Mac. The Mac App Store edition is coming soon.'
    : apple ? 'Get Trayage on the Mac App Store. The direct edition is still in preparation.'
    : 'Trayage is in development. The Mac build includes confirmed Trash cleanup, with release verification still underway. Check the download page for the status of each edition.';
  const categories = [['all','tray','All files'],['installers','drive','Disk images'],['duplicates','files','Likely duplicates'],['old','clock','Old or large']];
  const samples = [
    ['installers','drive','Studio-Installer.dmg','248 MB','Installer download','dmg'],
    ['duplicates','files','Invoice (1).pdf','3.2 MB','Likely duplicate','pdf'],
    ['old','folder','Project-archive.zip','1.4 GB','Large file','zip'],
    ['old','files','Workshop-notes.pdf','12 MB','Older file','pdf'],
    ['new','folder','Weekend-map.png','4.8 MB','Recently added','png']
  ];
  const cta = (plan, label) => site.checkoutEnabled ? `<a class="button full" href="${site.links[plan]}">${label} ${arrow}</a>` : `<a class="button full secondary" href="${base}download/">${hasDownload(releases)?'Get Trayage':'Check availability'} <span aria-hidden="true">→</span></a>`;
  const vibeRank = `<a class="viberank-badge" href="${escape(site.links.vibeRank)}"><img class="badge-light" src="https://viberank.dev/badge?app=Trayage&amp;theme=light" alt="Trayage on VibeRank" width="250" height="54" loading="lazy" decoding="async" referrerpolicy="no-referrer"><img class="badge-dark" src="https://viberank.dev/badge?app=Trayage&amp;theme=dark" alt="Trayage on VibeRank" width="250" height="54" loading="lazy" decoding="async" referrerpolicy="no-referrer"></a>`;
  return `<section class="hero wrap" aria-labelledby="hero-title">
    <div class="hero-copy"><p class="eyebrow"><span class="status-dot"></span> A home for your Downloads habit</p><h1 id="hero-title">Less digging.<br>More <em>finding.</em></h1><p class="hero-description">That installer from last month. The same PDF, twice. Trayage helps you make sense of your Downloads, one thoughtful review at a time.</p><div class="hero-actions"><a class="button" href="${hasDownload(releases) ? base + 'download/' : '#overview'}">${hasDownload(releases) ? 'Get Trayage' : 'Take a closer look'} <span aria-hidden="true">${hasDownload(releases) ? '↗' : '↓'}</span></a><a class="text-link" href="#pricing">See pricing ${arrow}</a></div><p class="hero-footnote">${icon('mac')} Made for macOS ${releases.minimumMacOS} and later <span class="mini-dot" aria-hidden="true"></span> ${hasDownload(releases) ? 'Available now' : 'In development'}</p><div class="community-badges">${vibeRank}</div></div>
    <figure class="product-figure"><div class="desktop-stage"><div class="stage-grain"></div><div class="desktop-menubar" aria-hidden="true"><span>Trayage</span><span>${icon('tray')} &nbsp; Wed 9:41</span></div><div class="review-window"><div class="window-chrome"><span class="traffic-lights" aria-hidden="true"><i></i><i></i><i></i></span><span>Downloads review</span><span class="window-mark">${icon('tray')}</span></div><div class="review-body"><div class="demo-sidebar"><div class="sidebar-title">YOUR DOWNLOADS</div><div class="demo-filters" hidden role="group" aria-label="Filter illustrative files">${categories.map(([id,ico,label],i)=>`<button type="button" data-filter="${id}" aria-pressed="${i === 0}">${icon(ico)}<span>${label}</span></button>`).join('')}</div><div class="sidebar-bottom">${icon('shield')} Reviewed locally</div></div><div class="demo-content"><div class="demo-heading"><div><p class="eyebrow">A little perspective</p><h2 id="demo-heading">All files</h2></div><span class="sample-badge">Sample files</span></div><div class="file-list">${samples.map(([group,ico,name,size,reason,type])=>`<div class="file-row" data-category="${group}"><span class="file-icon ${type}">${icon(ico)}</span><div class="file-info"><span class="file-name">${name}</span><span class="file-reason">${reason}</span></div><span class="file-size">${size}</span></div>`).join('')}</div><div class="demo-caption" id="demo-status" role="status" aria-live="polite">5 sample files · Explore the categories</div></div></div><div class="window-footer">${icon('shield')} File review stays on your Mac.<span>Read-only preview</span></div></div><div class="stage-label"><span class="tiny-cross" aria-hidden="true">+</span> A CLEARER VIEW OF WHAT’S IN THERE.</div></div><figcaption>Interactive illustration with sample files. Not an app screenshot.</figcaption></figure>
  </section>
  <div class="principles wrap"><p>${icon('mac')} Native to your Mac</p><p>${icon('shield')} Local file analysis</p><p>${icon('tray')} A focused Downloads review</p><p>${icon('check')} Your files, your decisions</p></div>
  <section class="section wrap overview" id="overview" aria-labelledby="overview-title"><div class="section-heading"><p class="eyebrow">A second look, without the search</p><h2 id="overview-title">The useful stuff.<br>The <em>used-to-be-useful</em> stuff.</h2><p>Downloads collect quickly. Trayage brings a few helpful signals together so you can see what deserves your attention.</p></div><div class="feature-grid">
    <article class="feature"><span class="feature-number">01 /</span>${icon('drive')}<h3>Installers that stayed over</h3><p>Find disk images in your Downloads. Trayage also checks for a similarly named app in Applications, as a clue that you may be finished with an installer.</p><span class="feature-label">Disk images</span></article>
    <article class="feature"><span class="feature-number">02 /</span>${icon('files')}<h3>The familiar-looking copies</h3><p>Spot likely repeats by filename and file size. These are candidates for your review; matching contents have not been verified.</p><span class="feature-label">Likely duplicates</span></article>
    <article class="feature"><span class="feature-number">03 /</span>${icon('clock')}<h3>The big and the forgotten</h3><p>Bring files of at least 1 GB and files last modified 30 or more days ago into view. A useful starting point when you’re deciding what still matters.</p><span class="feature-label">Old or large files</span></article>
    <article class="feature"><span class="feature-number">04 /</span>${icon('folder')}<h3>The things you just saved</h3><p>Keep recent downloads in sight, alongside the files that have been there a while. Open a selected file’s location in Finder for a closer look.</p><span class="feature-label">Recent files & Finder</span></article>
  </div></section>
  <section class="workflow-section" id="how-it-works" aria-labelledby="workflow-title"><div class="wrap workflow"><div class="workflow-intro"><p class="eyebrow">Small app. Considered approach.</p><h2 id="workflow-title">A calmer way<br>to look things over.</h2><p>Trayage lives in your menu bar, with an optional Dock presence and a full review window when you need more room.</p><a class="text-link" href="${base}privacy/">How your data is handled ${arrow}</a></div><ol class="steps"><li><span class="step-number">01</span><div><h3>Choose your Downloads folder.</h3><p>Review files in Downloads, or choose another folder. The current scan looks at that folder’s top-level files.</p></div></li><li><span class="step-number">02</span><div><h3>See why each file stands out.</h3><p>Browse by category, inspect file details, and reveal a file in Finder. File review happens locally on your Mac.</p></div></li><li><span class="step-number">03</span><div><h3>Decide what deserves to stay.</h3><p>Ignore a suggestion for the current review, or select files to move to Trash. Trayage asks you to confirm before cleanup.</p></div></li></ol></div></section>
  <section class="section wrap pricing" id="pricing" aria-labelledby="pricing-title"><div class="section-heading centered"><p class="eyebrow">One purchase. Your choice to upgrade.</p><h2 id="pricing-title">A small place in your workflow.<br>A straightforward price.</h2><p>${direct && !site.checkoutEnabled ? `Try cleanup for ${site.pricing.trialDays} days or activate an existing license. New license purchases are still being finalized. The trial ends without an automatic charge.` : `Try the full cleanup experience for ${site.pricing.trialDays} days. Buy when you’re ready. The trial ends without an automatic charge.`}</p></div><div class="price-grid"><article class="price-card"><div class="plan-top"><h3>Trayage</h3><span class="plan-label">Pay once</span></div><p class="price"><span class="currency">US$</span>${site.pricing.oneTimeUSD}<span class="price-period"> once</span></p><p class="price-explainer">Keep the cleanup features you buy.<br>No subscription or recurring charge.</p><ul class="check-list"><li>${icon('check')} All Trayage ${site.pricing.majorVersion}.x updates included</li><li>${icon('check')} Purchased features stay unlocked after updates</li><li>${icon('check')} Up to ${site.pricing.directDeviceLimit} active Macs per direct license</li><li>${icon('check')} Optional major upgrades, discounted for owners</li></ul>${cta('oneTime','Buy Trayage')}<p class="plan-fine-print">${site.pricing.trialDays}-day trial · No automatic payment</p></article></div><p class="channel-note"><strong>${channelIsLive(releases,'appStore') ? 'Also available on the Mac App Store.' : 'The Mac App Store edition is coming soon.'}</strong> ${channelIsLive(releases,'appStore') ? 'Free download with in-app purchases.' : 'Planned as a free download with in-app purchases.'} File review is free. Try cleanup with an optional ${site.pricing.trialDays}-day trial, with no automatic charge, or buy the separate US$${site.pricing.oneTimeUSD} one-time in-app unlock. The App Store will show your local price and trial eligibility. The ${site.pricing.directDeviceLimit}-Mac limit applies only to direct licenses.</p><p class="pricing-links">Read the <a href="${base}terms/">purchase terms</a>, <a href="${base}refunds/">refund policy</a>, and <a href="${base}privacy/">privacy details</a>.</p></section>
  <section class="wrap availability" id="availability" aria-labelledby="availability-title"><img src="${base}assets/app-icon.png" width="100" height="100" alt="" loading="lazy"><div><p class="eyebrow"><span class="status-dot"></span> ${hasDownload(releases) ? 'Ready for your Mac' : 'Still on the workbench'}</p><h2 id="availability-title">${hasDownload(releases) ? 'Make a little room.' : 'A little more time in the tray.'}</h2><p>${availability}</p><p>Built for macOS ${releases.minimumMacOS} and later.</p></div><a class="button secondary" href="${base}download/">${hasDownload(releases) ? 'Get Trayage' : 'Check availability'} ${arrow}</a></section>
  <section class="wrap roadmap-teaser"><div><p class="eyebrow">The road ahead</p><h2>Follow what’s taking shape.</h2><p>See what’s planned, in progress, and completed. Each improvement has a place on the roadmap.</p></div><a class="text-link" href="${base}roadmap/">Explore the roadmap ${arrow}</a></section>
  <section class="section wrap support-teaser"><div><p class="eyebrow">A person on the other end</p><h2>Need a hand?</h2><p>Find a license, move to a new Mac, or ask Kyle a question.</p></div><div class="support-teaser-links"><a href="${base}support/">Help & common questions ${arrow}</a><a href="${site.links.licenses}">Find your license ${arrow}</a><a href="${site.links.billing}">Purchase receipts ${arrow}</a></div></section>`;
}
