import { escape, arrow } from './layout.mjs';
import { releaseSummary, directPriceSummary } from './_lib/releases.js';

export const data = {layout:'base.11ty.js', permalink:'/media-kit/index.html', path:'media-kit/', title:'Media kit', description:'Trayage facts, app icons, publisher artwork, screenshots, and contact details for reviewers and the media.', tags:['sitePages'], order:7};

export default function ({base, site, releases, press}) {
  const facts = [['App','Trayage'],['Tagline',press.tagline],['Developer / publisher',`${site.publisher} / ${site.publisherBrand}`],['Based in','Texas, United States'],['Platform',`macOS ${releases.minimumMacOS} and later`],['Availability',releaseSummary(releases)],['Direct price',directPriceSummary(releases, site)],['App Store offer',`${releases.appStore.status==='available'?'':'Planned: '}free download and file review; optional ${site.pricing.trialDays}-day cleanup trial; separate US$${site.pricing.oneTimeUSD} one-time in-app unlock (local price shown by Apple)`],['Trial',`${site.pricing.trialDays} days; no automatic charge`],['Updates',`All ${site.pricing.majorVersion}.x updates included; optional paid major upgrades`]];
  return `<div class="wrap document-header media-header"><div><a class="eyebrow back-link" href="${base}">← Back to Trayage</a><p class="eyebrow page-kicker">For reviewers & the media</p><h1>The details.<br>The right assets.</h1><p class="lede">A handy starting point for covering Trayage. Product facts, artwork, and a person to contact.</p><a class="button" href="${base}assets/media/trayage-media-kit.zip" download>Download media kit <span aria-hidden="true">↓</span></a><p class="document-meta">ZIP · Artwork, fact sheet${press.screenshots.length?', screenshots':''} & usage notes · Updated ${press.updated}</p></div><img class="media-hero-icon" src="${base}assets/media/trayage-icon-512.png" alt="Trayage app icon" width="240" height="240"></div>
  <div class="wrap media-layout"><aside class="media-sidebar"><nav aria-label="Media kit contents"><a href="#facts">At a glance</a><a href="#descriptions">About Trayage</a><a href="#artwork">Icons & artwork</a><a href="#screenshots">Screenshots</a><a href="#review-notes">Review notes</a><a href="#press-contact">Press contact</a></nav></aside><div class="media-content">
  <section id="facts"><p class="eyebrow">Quick reference</p><h2>Trayage at a glance.</h2><dl class="press-facts">${facts.map(([key,value])=>`<div><dt>${key}</dt><dd>${escape(value)}</dd></div>`).join('')}</dl><a class="text-link" href="${base}assets/media/fact-sheet.txt" download>Download the fact sheet ${arrow}</a></section>
  <section id="descriptions"><p class="eyebrow">In a few words</p><h2>About Trayage.</h2><div class="press-copy"><h3>Short description</h3><p>${escape(press.shortDescription)}</p></div><div class="press-copy"><h3>Longer description</h3><p>${escape(press.longDescription)}</p></div><h3>About the developer</h3><p>${escape(press.developerBio)}</p></section>
  <section id="artwork"><p class="eyebrow">Ready to use</p><h2>Icons & publisher artwork.</h2><p>Trayage keeps its own app icon. RelayByte identifies the studio behind it.</p><ul class="press-assets">${press.assets.map(asset=>`<li><div class="press-asset-preview ${asset.path.includes('paper')?'on-dark':''}"><img src="${base}${escape(asset.path)}" alt="" loading="lazy"></div><div><h3>${escape(asset.label)}</h3><p>${escape(asset.format)}</p><a href="${base}${escape(asset.path)}" download>Download <span class="sr-only">${escape(asset.label)}</span> ${arrow}</a></div></li>`).join('')}</ul></section>
  <section id="screenshots"><p class="eyebrow">The app itself</p><h2>Screenshots.</h2>${press.screenshots.length?`<p>Actual app captures with synthetic sample files. These images show a prerelease build; the released interface may change.</p><div class="press-screenshots">${press.screenshots.map(shot=>`<figure><a href="${base}${escape(shot.path)}" download><img src="${base}${escape(shot.path)}" alt="${escape(shot.alt)}" loading="lazy"></a><figcaption><strong>${escape(shot.title)}</strong><span>${escape(shot.caption)}</span><a href="${base}${escape(shot.path)}" download>Download <span class="sr-only">${escape(shot.title)}</span> ${arrow}</a></figcaption></figure>`).join('')}</div>`:`<p>Publication-ready app captures are being prepared. <a href="mailto:${site.email}?subject=Trayage%20press%20screenshots">Contact Kyle for screenshots or a guided look at the current build.</a> The homepage’s interactive illustration is not an app screenshot.</p>`}</section>
  <section id="review-notes"><p class="eyebrow">Helpful context</p><h2>A few details to get right.</h2><ul class="review-notes"><li>Trayage reviews one selected folder’s top-level files. Folder monitoring, configurable thresholds, content-hash verification, and persistent ignores are on the <a href="${base}roadmap/">roadmap</a>.</li><li>Likely duplicates are suggestions based on filename and size. Matching contents are not currently verified.</li><li>Selected, unchanged files move to Trash only after confirmation. Trayage does not empty the Trash or promise automatic cleanup.</li><li>File analysis happens locally. Purchases, license verification, and support involve the services described in the <a href="${base}privacy/">privacy policy</a>.</li><li>The ${site.pricing.directDeviceLimit}-Mac device limit applies to direct licenses. Apple purchase and trial eligibility are managed through Apple.</li></ul><h3>Using the assets</h3><p>You may use the supplied artwork and descriptions in editorial coverage of Trayage. Please preserve proportions and colors, give the icon room to breathe, and identify prerelease screenshots as such. Keep RelayByte publisher artwork separate from the Trayage app icon. Coverage does not imply endorsement, and a review copy never requires a positive review.</p><p>Credit: Trayage / RelayByte, by Kyle Reddoch. Apple’s names and marks belong to Apple Inc.</p></section>
  <section id="press-contact" class="press-contact"><p class="eyebrow">A person on the other end</p><h2>Questions, interviews,<br>or a review copy?</h2><p>Contact Kyle with your publication, deadline, and what you’d like to cover. Review access and preview builds are arranged individually.</p><a class="text-link" href="mailto:${site.email}?subject=Trayage%20media%20inquiry">${site.email} ${arrow}</a></section>
  </div></div>`;
}
