import { icon, arrow, policyPage } from './layout.mjs';
import { channelIsLive } from './_lib/releases.js';

export function support(base, site, releases) {
  const faqs = [
    ['Where can I download Trayage?', `Visit the <a href="${base}download/">download page</a> for the current availability of the direct and Mac App Store editions. Each edition has its own download and purchase path.`],
    ['How does the '+site.pricing.trialDays+'-day trial work?', `The direct Mac edition starts a ${site.pricing.trialDays}-day trial in the app through Keylight. No payment is needed to start it. When it ends, you can still review files; cleanup requires a purchase. Buying charges US$${site.pricing.oneTimeUSD} once and does not begin another trial. The App Store edition offers free file review and a separate, optional ${site.pricing.trialDays}-day trial through Apple; restoring that trial does not restart its clock.`],
    ['Will I be charged when the trial ends?', 'No. The trial does not convert to a subscription or charge you automatically. You decide whether to make the one-time purchase. There is nothing to cancel.'],
    ['How do I activate my license?', 'For a direct purchase, Keylight emails a license key to the address used at checkout. In Trayage, open Settings, find “Enter License,” paste the complete TRAY license key, and choose “Activate License.” An internet connection is needed to activate and verify access. The App Store edition uses Apple purchases and Restore Purchases instead of license keys.'],
    ['I paid, but I can’t find the license email.', `For a direct purchase, check spam and the email address used at checkout, then use the <a href="${site.links.licenses}">Keylight license portal</a>. If it still isn’t there, <a href="mailto:${site.email}">email Kyle</a> with your purchase email and receipt reference. Please don’t send your full payment card details or full license key.`],
    ['Can I move my license to another Mac?', `Each direct-purchase license permits ${site.pricing.directDeviceLimit} active Macs. Choose “Deactivate This Mac” in Trayage’s Settings, or remove an old activation in the <a href="${site.links.licenses}">Keylight portal</a>. Then activate your key on the new Mac. The direct license limit does not govern App Store purchases.`],
    ['What does the one-time purchase include?', `The direct US$${site.pricing.oneTimeUSD} purchase includes Trayage and all ${site.pricing.majorVersion}.x updates on up to ${site.pricing.directDeviceLimit} active Macs. Your purchased cleanup features stay unlocked when the app updates. There is no recurring charge.`],
    ['Will I have to buy the next major version?', 'No. Future major upgrades will be optional and discounted for existing owners. You can keep using your purchased features and skip an upgrade. New features, eligibility, and the upgrade price will be explained before you buy. No future release date or fixed upgrade price is promised.'],
    ['Are duplicate matches certain?', 'No. The current scanner compares normalized filenames and file sizes. It does not compare file contents or calculate content hashes. Treat those matches as likely duplicates and review them yourself.'],
    ['Does Trayage upload my Downloads?', `The file review code runs locally and does not upload filenames or file contents for analysis. The direct app connects to Keylight for licensing, trial state, and device reporting. Purchases open Stripe in your browser. See the <a href="${base}privacy/">privacy policy</a> for the data flow and App Store edition.`],
    ['Can I use Trayage offline?', 'File review is local. Direct-license activation and periodic validation need an internet connection. Keylight can validate a cached license locally within its offline allowance; permanent offline access is not promised. If a license check fails, reconnect and select “Check License” in Settings.'],
    ['How do refunds work?', `The direct-purchase policy allows refund requests within ${site.pricing.directRefundDays} days of the initial payment. This is separate from the ${site.pricing.trialDays}-day trial. Apple handles App Store refund requests under its own rules. Read the <a href="${base}refunds/">refund policy</a>.`]
  ];
  if (channelIsLive(releases, 'direct') && !site.checkoutEnabled) {
    faqs.splice(1, 0, ['Can I buy a new direct license?', `New license purchases are still being finalized. You can <a href="${base}download/">download Trayage</a>, start a ${site.pricing.trialDays}-day trial, or activate an existing license. After the trial, file review remains available; cleanup requires an active license.`]);
  }
  return `<section class="wrap document-header support-header"><p class="eyebrow">Support, from the person who makes it</p><h1>Let’s get you<br><em>sorted.</em></h1><p class="lede">Your license, your next Mac, or something that doesn’t look right. Here’s where to start.</p></section>
  <section class="wrap help-cards" aria-label="Support options"><article><span class="help-icon">${icon('key')}</span><h2>Direct license & devices</h2><p>Recover a Keylight license and manage the three active Macs included with a direct purchase.</p><a class="text-link" href="${site.links.licenses}">Open Keylight portal ${arrow}</a></article><article><span class="help-icon">${icon('clock')}</span><h2>Direct billing & receipts</h2><p>For direct purchases: find purchase records, recover a receipt, or ask about a charge.</p><a class="text-link" href="${site.links.billing}">Open Stripe billing ${arrow}</a></article><article><span class="help-icon">${icon('mail')}</span><h2>Talk to Kyle</h2><p>For either edition, include your macOS version, Trayage version, and what you were trying to do.</p><a class="text-link email-link" href="mailto:${site.email}">${site.email} ${arrow}</a></article></section>
  <section class="wrap support-channels" aria-labelledby="apple-help"><p class="eyebrow">Mac App Store</p><h2 id="apple-help">Apple purchase help</h2><p>The App Store edition uses your Apple Account for in-app purchases and restoring access. Apple manages billing and refund decisions; Kyle provides help with Trayage. These links are Apple’s general support tools.</p><div class="channel-actions"><a class="text-link" href="${site.links.appleRefunds}">Request an Apple refund ${arrow}</a></div></section>
  <section class="wrap section faq-section" aria-labelledby="faq-title"><div><p class="eyebrow">A few helpful answers</p><h2 id="faq-title">Good questions.</h2><p>Direct purchases and the Mac App Store edition have different billing tools.</p></div><div class="faq-list">${faqs.map(([q,a],i)=>`<details${i===0?' open':''}><summary>${q}<span aria-hidden="true">+</span></summary><div class="faq-answer"><p>${a}</p></div></details>`).join('')}</div></section><div class="wrap support-note">${icon('shield')}<p>You never need to send your full card number, your full license key, or private Downloads to get help. Redact personal information from screenshots.</p></div>`;
}

export function privacy(base, site) {
  return policyPage({ site, base, path:'privacy/', title:'Privacy, in plain sight.', intro:'File review stays on your Mac. This policy explains the website, direct and App Store editions, purchases, and support.', sections:[
    {id:'who',title:'Who is responsible',content:`<p>Trayage is published by Kyle Reddoch under the RelayByte brand, operating in Texas, United States. Contact <a href="mailto:${site.email}">${site.email}</a> about this policy or a privacy request. This policy covers Trayage’s direct Mac app, Mac App Store edition, website, and support. “Kyle,” “we,” and “us” mean Kyle Reddoch, trading under the RelayByte brand.</p>`},
    {id:'files',title:'Your files stay on your Mac',content:'<p>Trayage reads top-level file names, sizes, types, and available creation, modification, and access dates in the folder being reviewed. It uses those details to suggest categories. For disk images, it also checks whether a similarly named app exists in Applications. The scanner does not upload file names, file contents, or scan results for analysis.</p><p>The app saves settings, the selected folder path, and a macOS folder-access bookmark locally. Review suggestions are held in memory. In the direct edition, Keylight stores license and trial state in device-bound encrypted storage. You can change or clear folder access in Settings. This does not delete billing or licensing records held by providers.</p>'},
    {id:'licensing',title:'Direct licensing and trials',content:`<p>The direct edition connects to Keylight to activate and validate licenses, retrieve licensing settings, and report trial or unlicensed status. This also happens without a purchase. </p><p>Reported information includes a stable installation identifier, a one-way device hash, the Mac’s computer name during activation, license or trial state, app and SDK versions, operating-system information, CPU architecture, and broad CPU-core and memory ranges. The computer name may include a person’s name. Requests expose a network address to the service. Keylight records activation and request activity; trial or unlicensed status is reported at launch, when state changes, and periodically while the app runs.</p><p>These records support license delivery, activation limits, trial management, and installation and trial-to-purchase conversion reporting. The device hash is derived from the Mac’s hardware identifier; the raw hardware identifier stays local. The hash and installation identifier are pseudonymous, not anonymous, and may become associated with a license and purchase email. These reports do not include your scanned files.</p><p>Read <a href="${site.links.keylightPrivacy}">Keylight’s privacy policy</a> and the <a href="${site.links.keylightSDK}">SDK release notes</a>. The direct edition uses these reports for trial and license administration and conversion statistics. It has no in-app switch that disables all SDK reporting. Contact Kyle about access to or deletion of licensing records.</p>`},
    {id:'payments',title:'Direct purchases',content:`<p>Stripe hosts direct checkout and the billing portal. It processes the email address, billing and payment information, transaction records, and technical information needed for payment and fraud prevention. This website has no embedded payment form and does not receive your full card details.</p><p>Kyle can access customer and transaction records in Stripe. Stripe sends purchase and refund events to Keylight, which connects the purchase email and order to a license and emails the key. A refund can change that license’s access. Kyle can access customer licensing records and device activity through Keylight.</p><p>These providers also have their own legal and service obligations. Their pages may use cookies. Read <a href="${site.links.stripePrivacy}">Stripe’s privacy policy</a> and <a href="${site.links.keylightPrivacy}">Keylight’s privacy policy</a>.</p>`},
    {id:'apple',title:'Mac App Store edition',content:`<p>The Mac App Store edition uses Apple’s purchase system instead of Stripe checkout and Keylight licensing. Apple processes purchases using your Apple Account; its handling of account, payment, purchase, and device information is explained in <a href="${site.links.applePrivacy}">App Store & Privacy</a>.</p><p>Trayage reads and verifies Apple purchase and entitlement information to manage the optional seven-day cleanup trial, unlock paid features, and restore purchases. The App Store edition excludes Stripe checkout and Keylight licensing. Apple manages purchase records under its own policy. Kyle does not receive your full card details from Apple.</p>`},
    {id:'website',title:'Website and appearance settings',content:`<p>This is a static website with no advertising, analytics scripts, tracking pixels, third-party fonts, or cookies set by its own code. The sample file illustration uses fictional data and does not access your files. External services are contacted when you follow their links.</p><p>Appearance follows your device’s light or dark setting by default. If you choose Light or Dark, this website saves only that choice in your browser under <code>trayage-appearance</code>. It is not an identifier and is not sent to Kyle. Selecting System removes the saved preference; clearing this site’s browser storage removes it too.</p><p>GitHub Pages hosts this website and receives connection and request information, including IP addresses, when serving pages. Read <a href="${site.links.githubPrivacy}">GitHub’s privacy statement</a>.</p>`},
    {id:'support',title:'Support through Proton Mail',content:`<p>Kyle uses Proton Mail for <a href="mailto:${site.email}">${site.email}</a>. When you ask for help, Kyle receives your email address, message, and any attachments you send, and uses them to answer you, investigate the issue, or locate a purchase.</p><p>Proton processes and stores this correspondence. Its <a href="${site.links.protonPrivacy}">Mail privacy policy</a> explains email metadata, spam screening, encryption, and storage. Ordinary email exchanged with other providers is not automatically end-to-end encrypted. Please redact private file names and other sensitive information from screenshots; do not send full card numbers or complete license keys.</p>`},
    {id:'use',title:'Use, sharing, and processing locations',content:'<p>We use this information to provide the app and purchases, manage trials and licenses, answer support requests, prevent fraud, maintain security, and meet accounting or legal obligations. The app and site contain no advertising integration or data-broker integration. Kyle does not sell personal information or use it for targeted advertising.</p><p>Kyle operates in the United States. Providers may process information in other countries under the policies linked above. Information may also need to be disclosed to comply with law or resolve a legal claim. This is not permission for unrelated marketing.</p><p>We use information needed to deliver requested software and purchases, provide support, protect the service against abuse, and meet legal obligations. Where consent is required for a particular use, we obtain it and explain how to withdraw it. We require service providers processing information on our behalf to protect it and use it only for the service and applicable legal obligations.</p>'},
    {id:'retention',title:'Retention and privacy requests',content:`<p>Email <a href="mailto:${site.email}">${site.email}</a> to request access, correction, or deletion of information held for Trayage. Depending on the law that applies, you may also request portability, object to or restrict a use, withdraw consent for a consent-based use, appeal a refused request, or complain to a regulator. A request may require a proportionate ownership check; never send your full payment card or license key.</p><p>Deactivating a Mac frees an activation; it does not erase the purchase record. Uninstalling the app does not remove provider records. Some information may need to remain for an active license, accounting, disputes, or legal obligations. A privacy request will be handled separately from a refund request.</p><p>We retain support messages while needed to resolve your request and related follow-up. Licensing records are retained while needed to administer trial limits, prevent abuse, and honor purchased access; payment records are retained for accounting, tax, fraud prevention, and legal obligations. Retention depends on the record’s purpose and applicable requirements. We review deletion requests with the relevant provider and explain any records that must be retained. Provider backup and legal-retention requirements may continue after deletion from active records.</p>`},
    {id:'changes',title:'Children and policy changes',content:`<p>Trayage is not directed to children under 13, and we do not knowingly collect their personal information. If you believe a child has provided information, contact Kyle to request its removal.</p><p>This policy is effective ${site.effective}. We update this page when the app, providers, or data uses change and provide additional notice or obtain consent when required by applicable law.</p>`}
  ]});
}

export function terms(base, site) {
  return policyPage({site,base,path:'terms/',title:'Purchase terms.',intro:'Pay once for Trayage. Keep your purchased features. Choose whether to buy future major upgrades.',sections:[
    {id:'publisher',title:'Publisher and availability',content:`<p>Trayage is published by Kyle Reddoch under the RelayByte brand, operating in Texas, United States. For support, contact <a href="mailto:${site.email}">${site.email}</a>. These terms cover the website, the direct Trayage license, and the purchase conditions described below. By using Trayage or buying a direct license, you agree to the terms applicable to that use or purchase, subject to your non-waivable rights.</p><p>The <a href="${base}download/">download page</a> identifies available editions. A product description or roadmap entry does not mean a particular edition or future feature is available. Purchases apply to the edition and features identified when you order.</p>`},
    {id:'plans',title:'One-time direct purchase',content:`<dl class="policy-definitions"><div><dt>Trayage — US$${site.pricing.oneTimeUSD} once</dt><dd>Includes the purchased cleanup features and all Trayage ${site.pricing.majorVersion}.x updates. There is no subscription, renewal, or automatic charge.</dd></div><div><dt>${site.pricing.directDeviceLimit} active Macs per direct license</dt><dd>Deactivate an old Mac to free a place for a new one. This is not an App Store device restriction.</dd></div></dl><p>Direct prices are in US dollars. Review the total, applicable tax, and supported payment method at checkout before paying.</p>`},
    {id:'trial',title:'Seven-day trial and digital delivery',content:`<p>The direct edition has a ${site.pricing.trialDays}-day in-app trial through Keylight, beginning on first launch. No payment is needed to start it, and it ends without an automatic charge. File review remains available afterward; cleanup requires a paid license. A purchase charges US$${site.pricing.oneTimeUSD} once at checkout and does not begin another trial.</p><p>Trayage is digitally delivered software; there is no physical shipment or shipping charge. After successful payment, Keylight creates the license and emails the key to your checkout address. Activate it in Trayage’s Settings. If delivery or activation fails, contact support with your purchase email and receipt reference.</p>`},
    {id:'upgrades',title:'Updates and optional major upgrades',content:`<p>Your purchased Trayage cleanup features remain unlocked when the app updates. All ${site.pricing.majorVersion}.x updates are included. You do not have to buy a future major upgrade to retain those purchased features.</p><p>Future major upgrades will be optional, with discounted pricing for existing owners. Any new paid capabilities, eligibility requirements, and upgrade price will be shown before purchase. You may skip an upgrade. No particular future feature, release date, or fixed upgrade price is promised.</p><p>Purchased access does not promise compatibility with every future macOS release or indefinite operation of online licensing services. Supported macOS versions and any published support policy apply.</p>`},
    {id:'license',title:'Direct software license',content:`<p>A direct purchase grants you a limited, non-exclusive license to use the purchased features for your personal or professional work on up to ${site.pricing.directDeviceLimit} Macs you own or control. It does not transfer ownership of the software or create a shared team license. Keep the key private; do not sell, rent, sublicense, or distribute it to other people. Contact Kyle about a change of owner or a team purchase.</p><p>Do not bypass license enforcement or distribute modified copies as Trayage. These terms do not restrict activities that applicable law expressly permits despite a contractual restriction. You retain ownership of your files.</p><p>Activation and periodic validation require access to Keylight. Cached licenses can be validated locally within the provider’s offline allowance. Revocation takes effect when updated license information is obtained, subject to that allowance. Permanent offline access is not promised. Manage activations in the <a href="${site.links.licenses}">Keylight portal</a>.</p>`},
    {id:'apple',title:'Mac App Store purchases',content:`<p>The Mac App Store edition is a free download with in-app purchases. File review is free. Cleanup requires the optional ${site.pricing.trialDays}-day trial or a separate US$${site.pricing.oneTimeUSD} one-time in-app unlock. Apple’s purchase screen will show your local price and eligibility. The trial ends without an automatic charge; buying the full unlock is a separate choice. Restoring a trial does not restart its original seven-day period.</p><p>That edition is licensed under <a href="${site.links.appleEULA}">Apple’s standard End User License Agreement</a>, together with applicable Apple usage rules. Direct Keylight keys and the ${site.pricing.directDeviceLimit}-Mac cap do not apply. Restore Purchases restores verified Apple ownership; purchased features remain available when the app updates, subject to a refund or revocation.</p><p>Apple decides App Store refund requests, while Kyle provides technical support. Buying through one route does not include a second license through the other route; no cross-store entitlement or migration offer is included.</p>`},
    {id:'review',title:'Your files and product limits',content:'<p>Trayage supports macOS 14 and later and supplies suggestions, not a guarantee that a file is unnecessary. Likely duplicates are based on names and sizes, not verified identical contents. A matching application name is a clue about an installer, not proof that it is safe to remove.</p><p>Trayage lets you review, reveal, and ignore suggestions, and move selected files to Trash after confirmation. Keep backups and review files yourself before cleanup. This guidance does not exclude any remedy required by consumer law.</p>'},
    {id:'rights',title:'Consumer rights and applicable law',content:'<p>These direct-purchase terms use Texas law, except where mandatory law gives you rights that cannot be waived. Nothing in these terms or the voluntary refund policy excludes those rights. If a problem cannot be resolved through support, you keep the dispute-resolution rights available under applicable law.</p><p>Trayage’s suggestions are provided to help your review and are not a warranty that a file is safe to remove, that all duplicates will be found, or that the software will be uninterrupted or error-free. To the extent applicable law permits, the software is provided as is without additional implied warranties. This does not limit any mandatory warranty, remedy, or responsibility that cannot lawfully be excluded. Nothing here excuses fraud, intentional misconduct, or liability that the law does not allow us to exclude.</p><p>We may update these terms for future use or purchases. Changes do not remove a purchased entitlement or retroactively reduce rights from an earlier purchase. The effective date is shown at the top of this page.</p>'}
  ]});
}

export function refunds(base, site) {
  return policyPage({site,base,path:'refunds/',title:'Room to change your mind.',intro:`For direct purchases: ${site.pricing.directRefundDays} days to request an initial-purchase refund, separate from the ${site.pricing.trialDays}-day trial. Apple handles App Store refunds.`,sections:[
    {id:'initial',title:'Direct initial purchases: 14 days',content:`<p>We accept refund requests within ${site.pricing.directRefundDays} days of the initial payment for the one-time license. The window begins with payment, not with the ${site.pricing.trialDays}-day in-app trial.</p><p>An eligible initial purchase receives a full refund, including tax charged on it, with no reason required. Feedback is welcome but is not a condition of eligibility. Send the request within the window; it does not depend on when Kyle replies.</p>`},
    {id:'trial',title:'Trial and future upgrades',content:`<p>The ${site.pricing.trialDays}-day trial ends without charging you, so there is no trial payment to refund or subscription to cancel. You choose whether to buy.</p><p>Future major upgrades are separate, optional purchases. Their price and applicable refund terms will be stated before purchase. An upgrade refund must preserve any earlier, separately purchased entitlement that has not itself been refunded or revoked.</p>`},
    {id:'request',title:'Request a direct refund',content:`<ol><li>Email <a href="mailto:${site.email}?subject=Trayage%20refund%20request">${site.email}</a> with the subject “Trayage refund request.”</li><li>Include your purchase email, payment date, and Stripe receipt or invoice reference if available.</li><li>For a billing error, briefly explain what happened. An explanation is not required for an initial request within ${site.pricing.directRefundDays} days under this policy.</li></ol><p>Do not send your full card number or license key. If you lost the receipt or access to the purchase email, say so; support can help verify the purchase.</p>`},
    {id:'errors',title:'Duplicate charges and billing errors',content:`<p>Report a suspected duplicate or incorrect direct charge even if more than ${site.pricing.directRefundDays} days have passed. We investigate and correct verified billing errors without treating the voluntary refund window as a deadline for reporting them.</p><p>For a partial refund, Kyle will explain the amount and remaining access before processing it. Any applicable legal entitlement to a refund remains separate.</p>`},
    {id:'after',title:'After a direct refund',content:'<p>An approved refund is submitted through Stripe to the original payment method where supported. Bank and provider processing times vary. Kyle will confirm the result; no fixed bank arrival time is promised.</p><p>A full refund of the initial purchase revokes the associated paid license. A refund of a duplicate charge must preserve the valid, separately paid entitlement.</p><p>The app receives changed license status when it refreshes, subject to the offline allowance. A refund does not delete files on your Mac.</p>'},
    {id:'apple',title:'App Store refunds',content:`<p>For purchases billed by Apple, request a refund through <a href="${site.links.appleRefunds}">Apple’s Report a Problem service</a>. Apple decides eligibility and processes the refund under its rules and applicable law. The direct ${site.pricing.directRefundDays}-day policy above does not set Apple’s refund terms.</p><p>Kyle can help with a Trayage technical issue, but cannot issue a Stripe refund for an Apple charge.</p>`},
    {id:'rights',title:'Your consumer rights',content:'<p>This voluntary policy does not reduce rights under applicable consumer law, including remedies for faulty or misdescribed software. A digital download is not, by itself, a blanket waiver of those rights.</p>'}
  ]});
}
