import { escape, icon, arrow } from './layout.mjs';

export const data = {layout:'base.11ty.js', permalink:'/roadmap/index.html', path:'roadmap/', title:'Roadmap', description:'Follow what is planned, in progress, and completed for Trayage, the Mac Downloads review app.', tags:['sitePages'], order:5};

export default function ({base, site, roadmap}) {
  const groups = [
    ['in-progress','In progress','What I’m working through now.'],
    ['planned','Planned','The next improvements on the list.'],
    ['completed','Completed','Built features stay here so you can follow the progress.']
  ];
  return `<div class="wrap document-header"><a class="eyebrow back-link" href="${base}">← Back to Trayage</a><p class="eyebrow page-kicker">The road ahead</p><h1>A little better,<br>one release at a time.</h1><p class="lede">Here’s what I’m building, what’s planned, and what’s already been completed.</p><p class="document-meta">Updated <time datetime="${roadmap.updated}">${new Date(roadmap.updated+'T12:00:00Z').toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'})}</time></p></div>
  <div class="wrap roadmap-intro"><p>Plans can change as I learn from testing and feedback. Items do not have a promised date or major version unless one is shown. Choose Trayage for the features available when you buy it; future major upgrades will be optional. Read version highlights in the <a href="${base}changelog/">changelog</a>.</p><nav class="roadmap-jump" aria-label="Roadmap status">${groups.map(([status,title])=>`<a href="#${status}">${title} <span>${roadmap.items.filter(i=>i.status===status).length}</span></a>`).join('')}</nav></div>
  <div class="wrap roadmap-board">${groups.map(([status,title,description])=>`<section class="roadmap-group" id="${status}" aria-labelledby="${status}-title"><div class="roadmap-group-heading"><span class="roadmap-indicator ${status}" aria-hidden="true">${status==='completed'?'✓':status==='in-progress'?'◐':'○'}</span><div><h2 id="${status}-title">${title}</h2><p>${description}</p></div><span class="roadmap-count">${roadmap.items.filter(i=>i.status===status).length} items</span></div><ul class="roadmap-items">${roadmap.items.filter(item=>item.status===status).map(item=>`<li class="roadmap-item" id="feature-${item.id}"><div class="roadmap-item-status">${status==='completed'?icon('check'):`<span aria-hidden="true">${status==='in-progress'?'◐':'○'}</span>`}<span>${item.release?`Released in ${escape(item.release.version)}`:status==='completed'?'Built · not released':title}</span></div><h3><a href="#feature-${item.id}">${escape(item.title)}</a></h3><p>${escape(item.description)}</p><div class="roadmap-item-meta"><span>${escape(item.area)}</span>${item.release?`<time datetime="${item.release.date}">${escape(item.release.date)}</time>${item.release.url?`<a href="${escape(item.release.url)}">Release notes ${arrow}</a>`:''}`:''}</div></li>`).join('')}</ul></section>`).join('')}</div>
  <section class="wrap roadmap-feedback"><div><h2>Something on your mind?</h2><p>Tell me what would make your next Downloads review easier.</p></div><a class="button secondary" href="mailto:${site.email}?subject=Trayage%20feature%20idea">Share an idea ${arrow}</a></section>`;
}
