import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { resolve, basename } from 'node:path';
import { zipSync, strToU8 } from 'fflate';
import { releaseSummary, directPriceSummary } from './releases.js';

export async function buildMediaKit(output, site, releases, press) {
  const destination = resolve(output, 'assets/media');
  await mkdir(destination, {recursive:true});
  const facts = `TRAYAGE — MEDIA FACT SHEET\nUpdated: ${press.updated}\n\n${press.tagline}\n\n${press.shortDescription}\n\nABOUT TRAYAGE\n${press.longDescription}\n\nAT A GLANCE\nDeveloper: ${site.publisher}\nPublisher brand: ${site.publisherBrand}\nLocation: Texas, United States\nPlatform: macOS ${releases.minimumMacOS} and later\nAvailability: ${releaseSummary(releases)}\nDirect price: ${directPriceSummary(releases, site)}\nApp Store offer: ${releases.appStore.status==='available'?'':'Planned: '}free download and file review; optional ${site.pricing.trialDays}-day cleanup trial; separate US$${site.pricing.oneTimeUSD} one-time in-app unlock (local price shown by Apple)\nTrial: ${site.pricing.trialDays} days; no automatic charge\nDirect license: ${site.pricing.directDeviceLimit} active Macs\nUpdates: Version ${site.pricing.majorVersion}.x included; future major upgrades optional and discounted for owners\n\nABOUT KYLE\n${press.developerBio}\n\nPRESS CONTACT\n${site.email}\n${site.origin?`Website origin: ${site.origin}\n`:''}\nACCURACY NOTES\nCurrent scans cover one selected folder's top-level files. Likely duplicates use filename and size, not verified matching contents. Ignore applies to the current review. File analysis stays local; payments, licenses and support use the services listed in the app's privacy policy. Cleanup requires confirmation and never empties the Trash. Folder monitoring, custom thresholds, content hashes, and persistent ignores remain planned; no release dates or version assignments are promised.\n\nSCREENSHOTS\n${press.screenshots.length?press.screenshots.map(s=>`${basename(s.path)}: ${s.title}. ${s.caption}`).join('\n'):'App screenshots are being prepared. Contact Kyle for current review access. Website illustrations are not app screenshots.'}\n`;
  const usage = `TRAYAGE MEDIA KIT\nUpdated ${press.updated}\n\nEditorial use\nYou may use the included artwork and descriptions in editorial coverage of Trayage. Preserve proportions, colors, and clear space. Identify prerelease screenshots as such. Do not use the RelayByte publisher symbol in place of Trayage's app icon. Copyright © 2026 ${site.publisherBrand}. Developer: ${site.publisher}. Credit: Trayage / RelayByte, by Kyle Reddoch. Coverage does not imply endorsement. Review access never requires a positive review.\n\n${press.screenshots.length?'Screenshots are actual app captures using synthetic sample files. See the fact sheet for edition, version and context.':'No app screenshots are included in this edition of the kit.'}\n\nThe product icon belongs to Trayage; the publisher artwork identifies RelayByte. Apple marks belong to Apple Inc. No Apple badge artwork is redistributed in this kit.\n\nQuestions, interviews or review access: ${site.email}\n`;
  await writeFile(resolve(destination,'fact-sheet.txt'),facts);
  await writeFile(resolve(destination,'README.txt'),usage);
  const files = {'Trayage Media Kit/fact-sheet.txt':strToU8(facts),'Trayage Media Kit/README.txt':strToU8(usage)};
  for (const asset of [...press.assets,...press.screenshots]) {
    if (!/^assets\/media\/[\w.-]+$/.test(asset.path)) throw new Error(`Media assets must live directly in assets/media: ${asset.path}`);
    files[`Trayage Media Kit/${basename(asset.path)}`] = new Uint8Array(await readFile(resolve(output,asset.path)));
  }
  await writeFile(resolve(destination,'trayage-media-kit.zip'),zipSync(files,{level:6}));
}
